version: "3.7"
services:
  mysqldb:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: productdb
      SPRING_DATASOURCE_URL: jdbc:msql://mysql:3306/productdb
      SPRING_DATABASE_USERNAME: root
      SPRING_DATABASE_PASSWORD: root
    ports:
      - 3308:3306
